### ISSUE TITLE
multus unable to call the plugin

### ISSUE THREAD

**Issue by raffaelespazzoli** [redhat-nfvpe/cni-route-override#5]
I'm getting this error when trying to use multus to call this plugin.
```
Failed create pod sandbox: rpc error: code = Unknown desc = failed to create pod network sandbox k8s_tcp-deploy-769fbf4795-7x4pj_sample_df31016a-c991-11e9-b9dd-023593b1f4d4_0(debd4844b00f541fe154147abd81e1458372849c1f7c42a761b07831eaed114b): Multus: Err in loading K8s Delegates k8s args: Multus: Err in getting k8s network from pod: GetPodNetwork: failed getting the delegate: getKubernetesDelegate: failed to get network resource, refer Multus README.md for the usage guide: the server could not find the requested resource
```
I'm running on OpenShift 4.1 and deployed the cni binary in the correct location: `/var/lib/cni/bin` via a modified daemonset. 
I created the multus config as follows:
```
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition 
metadata:
  name: sdn-tunnel 
spec:
  config: '{ 
        "type" : "route-override",
        "flushroutes" : false,
        "flushgateway" : false,
        "delroutes": [
        {
            "dst": "192.168.0.0/24"
        }],
        "addroutes": [
        {
            "dst": "192.168.0.0/24",
            "gw": "10.1.254.254"
        }]
    }'
```
I added the following annotation to a pod:
```
      annotations:
        k8s.v1.cni.cncf.io/networks: sdn-tunnel
```
which clearly takes effect because the pod is erring out now. 
What further troubleshooting can I do from here?

**Comment by s1061123** [comment]
Thank you for trying this plugin. This CNI plugin requires some CNI interface plugin (e.g. macvlan, ipvlan or others), which creates network interface because this CNI plugin does not create any network interface.

So you need to create config with interface CNI plugin and route-override as following.

```
{
    "cniVersion": "0.3.0",
    "name" : "mymacvlan",
    "plugins": [
    {
        "type": "macvlan",
        "master": "eth1",
        "mode": "bridge",
        "ipam": {
            ...
        }
    },
    {
        "type" : "route-override",
        "flushroutes" : "true",
        "delroutes": [
        {
            "dst": "192.168.0.0/24"
        }],
        "addroutes": [
        {
            "dst": "192.168.0.0/24",
            "gw": "10.1.254.254"
        }]
    }
    ]
}
```

**Comment by raffaelespazzoli** [comment]
@s1061123  I am using this plugin with [multus](https://github.com/intel/multus-cni) (it delegates to multiple cni plugins), so the default network configuration will be already in place by the time this plugin is called. 
What else does the plugin need?

**Comment by s1061123** [comment]
If you'd like to use it for delegate in multus.conf (in /etc/cni/net.d), you need to write it in the config, not net-attach-def.

**Comment by raffaelespazzoli** [comment]
I think I get it now. CNI expects you to create and return an interface, but this plugin doesn't. So it can't be used as the primary CNI plugin (the one that returns an actual interface), but only in the plugin section of a primary CNI plugin. in the case of multus in the networkattach definition, I need a primary CNI plugin, then I can use the `route-override` plugin as a plugin as in the example. Correct?

In my use case I don't need a new interface to be created, I just need to change the routing rules. How can I achieve that? Is there a dummy plugin? or maybe I could use the loopback CNI plugin?

**Comment by s1061123** [comment]
So you already have CNI plugin for cluster network in /etc/cni/net.d, "delegates", right?
You can change delegates CNI config to use "plugins" and add route-override CNI plugin after your CNI plugin.

```
    {
      "name": "multus-cni-network",
      "type": "multus",
      "capabilities": {
        "portMappings": true
      },
      "delegates": [
        {
          "cniVersion": "0.3.1",
          "name": "default-cni-network",
          "plugins": [
            {
              "type": "flannel",
              "name": "flannel.1",
                "delegate": {
                  "isDefaultGateway": true,
                  "hairpinMode": true
                }
              },
              {
                "type": "route-override",
                <ADD your config!>
              }
          ]
        }
      ],
      "kubeconfig": "/etc/cni/net.d/multus.d/multus.kubeconfig"
    }
```
